CREATE TABLE [dbo].[EMPRESA] (
    [ID]           UNIQUEIDENTIFIER NOT NULL,
    [RAZAOSOCIAL]  NVARCHAR (150)   NOT NULL,
    [NOMEFANTASIA] NVARCHAR (150)   NOT NULL,
    [CNPJ]         NVARCHAR (25)    NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
)




